import * as React from 'react';
import oncokbClient from 'app/shared/api/oncokbClientInstance';
import { CitationText } from 'app/components/CitationText';
import { AuthDownloadButton } from 'app/components/authDownloadButton/AuthDownloadButton';
import { Link } from 'react-router-dom';
import { PAGE_ROUTE } from 'app/config/constants';

export const DataAccessPage: React.FunctionComponent<{}> = () => {
  return (
    <>
      <h6>
        By using OncoKB data, you are agreeing to the OncoKB{' '}
        <Link to={PAGE_ROUTE.TERMS}>
          <u>usage terms</u>
        </Link>
        .
      </h6>
      <div className={'mb-3'}>
        <h3 className="title">Annotating Your Files</h3>
        <div>
          You can annotate your data files (mutations, copy number alterations, fusions, and clinical data) with{' '}
          <a href="https://github.com/oncokb/oncokb-annotator" target="_blank" rel="noopener noreferrer">
            OncoKB Annotator
          </a>
          .
        </div>
      </div>
      <div className={'mb-3'}>
        <h3 className="title">Web API</h3>
        <div>
          You can programmatically access the OncoKB data via its{' '}
          <a href="api/v1/swagger-ui.html" target="_blank" rel="noopener noreferrer">
            web API
          </a>
          . Clients to the API can be generated by{' '}
          <a href="https://swagger.io/tools/swagger-codegen/" target="_blank" rel="noopener noreferrer">
            Swagger Codegen
          </a>
          .
        </div>
      </div>
      <div className={'mb-3'}>
        <h3 className="title">Data Download</h3>
        <div>
          OncoKB annotations are fully available for download. Please review the{' '}
          <a href="terms">
            <u>usage terms</u>
          </a>{' '}
          before downloading. Previous versions are available{' '}
          <a href="https://github.com/oncokb/oncokb-public/tree/master/data" target="_blank" rel="noopener noreferrer">
            here
          </a>
          .
        </div>
      </div>
      <div className={'mb-3'}>
        <CitationText />
      </div>
      <div>
        <AuthDownloadButton
          fileName="allCuratedGenes.tsv"
          getDownloadData={() => oncokbClient.utilsAllCuratedGenesTxtGetUsingGET({})}
          buttonText="All Curated Genes"
        />
        <AuthDownloadButton
          fileName="allAnnotatedVariants.tsv"
          getDownloadData={() => oncokbClient.utilsAllAnnotatedVariantsTxtGetUsingGET({})}
          buttonText="All Curated Alterations"
        />
        <AuthDownloadButton
          fileName="allActionableVariants.tsv"
          getDownloadData={() => oncokbClient.utilsAllActionableVariantsTxtGetUsingGET({})}
          buttonText="Actionable Alterations"
        />
      </div>
    </>
  );
};
