export const enum MailType {
  ACTIVATION = 'ACTIVATION',
  APPROVAL = 'APPROVAL',
  CREATION = 'CREATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  LICENSE_REVIEW_COMMERCIAL = 'LICENSE_REVIEW_COMMERCIAL',
  LICENSE_REVIEW_RESEARCH_COMMERCIAL = 'LICENSE_REVIEW_RESEARCH_COMMERCIAL',
  LICENSE_REVIEW_HOSPITAL = 'LICENSE_REVIEW_HOSPITAL',
  CLARIFY_ACADEMIC_FOR_PROFIT = 'CLARIFY_ACADEMIC_FOR_PROFIT',
  CLARIFY_ACADEMIC_NON_INSTITUTE_EMAIL = 'CLARIFY_ACADEMIC_NON_INSTITUTE_EMAIL',
  TEST = 'TEST'
}
