export const enum MailType {
  ACTIVATION,
  APPROVAL,
  CREATION,
  PASSWORD_RESET,
  LICENSE_REVIEW_COMMERCIAL,
  LICENSE_REVIEW_RESEARCH_COMMERCIAL,
  LICENSE_REVIEW_HOSPITAL,
  CLARIFY_ACADEMIC_FOR_PROFIT,
  CLARIFY_ACADEMIC_NON_INSTITUTE_EMAIL,
  TEST
}
